In [1]:
import pandas as pd

In [4]:
df = pd.read_parquet('/Users/julianeoliveira/Downloads/APS_dengue', engine='pyarrow')

In [5]:
df.columns

Index(['Uf', 'Ibge', 'Municipio', 'Atendimentos', 'populacao_estimada', 'Ano',
       'Mes', 'PC_COBERTURA_SF', 'PC_COBERTURA_AB', 'measure_1f_12',
       'd_measure_1f_12', 'q_measure_1f_12', 'PORTE_MUNICIPIO', 'UBS_Count',
       'Cód Região de Saúde', 'Nome da Região de Saúde', 'long', 'lat',
       'NM_MUN', 'SIGLA', 'AREA_KM2', 'Dengue'],
      dtype='object')

In [11]:
df.Ano.value_counts()

2021    65507
2020    64986
2019    64033
2018    63062
2017    60238
2022    33028
Name: Ano, dtype: int64

In [12]:
df.head()

,Uf,Ibge,Municipio,Atendimentos,populacao_estimada,Ano,Mes,PC_COBERTURA_SF,PC_COBERTURA_AB,measure_1f_12,...,PORTE_MUNICIPIO,UBS_Count,Cód Região de Saúde,Nome da Região de Saúde,long,lat,NM_MUN,SIGLA,AREA_KM2,Dengue
0,CE,230535,ICAPUÍ,2464,19685,2017,1,100,100,0.817741,...,PEQUENO,8.0,23007,7ª Região Aracati-CE,-37.410463,-4.738625,Icapuí,CE,421.440,0
1,PE,261050,PASSIRA,4329,28889,2017,1,100,100,1.276060,...,MEDIO,17.0,26006,Limoeiro-PE,-35.546453,-8.012348,Passira,PE,326.757,0
2,PE,261220,SALGUEIRO,5026,60453,2017,1,"91,82","91,82",0.077403,...,MEDIO,3.0,26011,Salgueiro-PE,-39.089847,-8.129101,Salgueiro,PE,1678.564,1
3,PB,251274,RIACHÃO,776,3607,2017,1,100,100,1.246145,...,PEQUENO,2.0,25002,2ª Região-PB,-35.647465,-6.541768,Riachão,PB,85.291,0
4,PA,150307,GARRAFÃO DO NORTE,1137,25363,2017,1,"68,06","68,06",1.917779,...,MEDIO,NaN,15008,Metropolitana III-PA,-47.075962,-2.168264,Garrafão do Norte,PA,1608.014,0

In [18]:
df = pd.read_csv('/Users/julianeoliveira/Downloads/bioclim_temperature_BR.csv')

In [19]:
df.head()

,geocode,datetime,CHG-bio01-count,CHG-bio01-sum,CHG-bio01-mean,CHG-bio01-sd,CHG-bio01-min,CHG-bio01-max,CHG-bio01-perc25,CHG-bio01-perc50,...,CHG-bio11-perc75,CHG-bio11-count_normalized,CHG-bio11-sum_normalized,CHG-bio11-mean_normalized,CHG-bio11-sd_normalized,CHG-bio11-min_normalized,CHG-bio11-max_normalized,CHG-bio11-perc25_normalized,CHG-bio11-perc50_normalized,CHG-bio11-perc75_normalized
0,110001,1981,228,68333.032913,299.706285,0.024697,299.651988,299.811016,299.697557,299.705943,...,298.189961,3.226254e-08,0.00001,4.217705e-08,2.206017e-11,4.213898e-08,4.222080e-08,4.215864e-08,4.217708e-08,507.429282
1,110001,1982,228,68295.785206,299.542918,0.027094,299.496849,299.604644,299.519437,299.540877,...,297.825248,3.226254e-08,0.00001,4.213982e-08,4.330552e-12,4.212720e-08,4.214615e-08,4.213809e-08,4.214059e-08,506.808649
2,110001,1983,228,68478.692645,300.345143,0.070353,300.217808,300.463753,300.284675,300.333051,...,299.274569,3.226254e-08,0.00001,4.234677e-08,2.944648e-12,4.233730e-08,4.235569e-08,4.234574e-08,4.234641e-08,509.274956
3,110001,1984,228,68266.720198,299.415439,0.068574,299.306557,299.528456,299.350799,299.416243,...,297.987084,3.226254e-08,0.00001,4.216198e-08,4.064917e-12,4.215306e-08,4.216895e-08,4.215816e-08,4.216208e-08,507.084045
4,110001,1985,228,68301.633596,299.568568,0.105628,299.414514,299.741425,299.464984,299.565444,...,297.888444,3.226254e-08,0.00001,4.215075e-08,2.490603e-12,4.214501e-08,4.215782e-08,4.214957e-08,4.215101e-08,506.916191

In [20]:
df.datetime.value_counts()

1981    5569
1982    5569
2003    5569
2004    5569
2005    5569
2006    5569
2007    5569
2008    5569
2009    5569
2010    5569
2011    5569
2012    5569
2013    5569
2014    5569
2015    5569
2016    5569
2017    5569
2018    5569
2019    5569
2002    5569
2001    5569
2000    5569
1990    5569
1983    5569
1984    5569
1985    5569
1986    5569
1987    5569
1988    5569
1989    5569
1991    5569
1999    5569
1992    5569
1993    5569
1994    5569
1995    5569
1996    5569
1997    5569
1998    5569
2020    5569
Name: datetime, dtype: int64